foreground            #262626
background            #f4f4f2
selection_foreground  #f4f4f2
selection_background  #697780
url_color             #697780

scrollback_lines      0

cursor                #262626
cursor_text_color     #f4f4f2

# black
color0                #f4f4f2
color8                #f4f4f2

# red
color1                #806f74
color9                #806f74

# green
color4                #707f6d
color10               #707f6d

# yellow
color3                #807d6d
color11               #807d6d

# blue
color2                #697780
color12               #697780

# magenta
color5                #796d80
color13               #796d80

# cyan
color6                #697d79
color14               #697d79

# white
color7                #707377
color15               #262626