# Colors
source = ~/.config/hypr/colors/colors.conf


# Sources
source = ~/.config/hypr/modules/Monitors.conf 
source = ~/.config/hypr/modules/Programs.conf
source = ~/.config/hypr/modules/Autostart.conf
source = ~/.config/hypr/modules/Env.conf
source = ~/.config/hypr/modules/Decoration.conf
source = ~/.config/hypr/modules/Windowrules.conf
source = ~/.config/hypr/modules/Layout.conf
source = ~/.config/hypr/modules/Misc.conf
source = ~/.config/hypr/modules/Inpute.conf
source = ~/.config/hypr/modules/Keybinds.conf

# Customizable Sources 
source = ~/.config/hypr/modules/Animations.conf

