###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus # gsettings set org.gnome.desktop.wm.preferences button-layout ":" (Use This in Terminal to hide Close icons)
$menu = pkill rofi || bash ~/.config/rofi/launcher.sh
$browser = zen-browser
$editor = code
$theme-launcher = ~/.config/colorschemes/theme-launcher.sh