#/*-----Apps-----*/#
$terminal = kitty
$fileManager = nautilus # gsettings set org.gnome.desktop.wm.preferences button-layout ":" (Use This in Terminal to hide Close icons)
$browser = zen-browser
$editor = code

#/*-----System Apps-----*/#
$menu = pkill rofi || rofi -show drun -theme ~/.config/rofi/applauncher.rasi
$waybar = ~/.config/waybar/scripts/launch.sh
$swaync =~/.config/swaync/Scripts/reload_nc.sh

$wlogout = ~/.config/wlogout/scripts/wlogout.sh
$hyprlock = hyprlock -c ~/.config/hypr/hyprlock/hyprlock.conf

$clipboard = ~/.config/hypr/scripts/clipboard-toggle.sh

#/*-----Switchers-----*/#
$theme-switcher = ~/.config/colorschemes/theme-switcher.sh
