windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#window

# ----- Layer rules -----

# Blur Waybar
#layerrule = match:namespace waybar, blur on
#layerrule = match:namespace waybar, ignore_alpha 0.5
#layerrule = match:namespace waybar, ignore_alpha 0.5
layerrule = match:namespace waybar, no_anim on

# Blur swaync
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on

layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5

layertrule = match:namespace notification-popups, animation fade

# Blur wlogout
layerrule = match:namespace logout_dialog, animation fade
layerrule = match:namespace logout_dialog, blur on

# Rofi
layerrule = match:namespace rofi, animation popin 90%
#layerrule = match:namespace rofi, blur on
#layerrule = match:namespace rofi, ignore_alpha 0.5 


# AGS
layertrule = animation fade, match:namespace corner-.*








